[program:webhook-deploy]
command=/var/www/users/webhook-deploy/webhook-deploy-bin
directory=/var/www/users/webhook-deploy
user=yourcompany
autostart=true
autorestart=true
startretries=5
stdout_logfile=/var/log/puge/webhook-deploy.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=3
redirect_stderr=true

environment=
    PORT="9000",
    GITHUB_WEBHOOK_SECRET="f0b47d984e1a6135bcbbec9003fdbdc83750e4504d78b7e5ca5c4e0e260926b9",
    ALLOWED_BRANCH="refs/heads/main",
    DEPLOY_SCRIPT_PATH="/var/www/users/webhook-deploy/deploy.sh",
    DEPLOY_HISTORY_PATH="/var/www/users/webhook-deploy/deploy_history.json"
